#cloud-config
packages:
  - snapd
runcmd:
  - snap install microk8s --classic
  - microk8s status --wait-ready
  - usermod -a -G microk8s ubuntu
  - echo "alias mkctl='microk8s kubectl'" >> /home/ubuntu/.profile
  - echo "alias mk='microk8s'" >> /home/ubuntu/.profile
  - source /home/ubuntu/.profile
